export const CarData = [
  {
    id: "1",
    name: "Sue gate F 1.0 for Sale",
    year: "2014",
    mileage: "2,000 km",
    country: "UK",
    fuel: "Petrol",
    cc: "1300cc",
    transmission: "Automatic",
    color: "black",
    make: "Toyota",
    model: "Corola",
    bodytype: "Wagon",
    price: "$4,000",
    steering: "Left Hand Drive",
    date: "2 November,2022",
  },
  {
    id: "4",
    name: "Sue gate F 1.0 for Sale",
    year: "2014",
    mileage: "2,000 km",
    country: "UK",
    fuel: "Petrol",
    cc: "1300cc",
    transmission: "Automatic",
    color: "black",
    make: "Toyota",
    model: "Corola",
    bodytype: "Wagon",
    price: "$4,000",
    steering: "Left Hand Drive",
    date: "2 November,2022",
  },
  {
    id: "2",
    name: "Sue gate F 1.0 for Sale",
    year: "2014",
    mileage: "2,000 km",
    country: "Japan",
    fuel: "Petrol",
    cc: "1300cc",
    transmission: "Automatic",
    color: "black",
    make: "Toyota",
    model: "Corola",
    bodytype: "Wagon",
    price: "$4,000",
    steering: "Left Hand Drive",
    date: "2 November,2022",
  },
  {
    id: "3",
    name: "Sue gate F 1.0 for Sale",
    year: "2014",
    mileage: "2,000 km",
    country: "Japan",
    fuel: "Petrol",
    cc: "1300cc",
    transmission: "Automatic",
    color: "black",
    make: "Toyota",
    model: "Corola",
    bodytype: "Wagon",
    price: "$4,000",
    steering: "Left Hand Drive",
    date: "2 November,2022",
  },
];
